### ISSUE TITLE
Out of Memory Error after backing up bigger directory

### ISSUE THREAD

**Issue by Prof-Bloodstone** [knoxite/knoxite#188]
Backing up big directory, when host has limited amount of RAM results in OOM.

It is weird, because it looks like the backup finished before knoxite crashed. Last thing I see on stdout:
```
22.09 GiB / 22.09 GiB (1,281,234 of 1,281,234)  11.52 MiB/s [################################################] 100.00%
Snapshot a4014232 created: 1279908 files, 1325 dirs, 1 symlinks, 0 errors, 22.09 GiB Original Size, 22.03 GiB Storage Size
```
As you can see the directory used for testing had 22GB.

## Commands ran
I've started my test script, which does:
```sh
knoxite repo init
knoxite volume init "My Volume"
/usr/bin/time -- knoxite store latest "/my/backup/path" --compression "none"
```

#### Knoxite
knoxite built from source - commit 52b83b01f598deea79d3fd1b0ec44f1e5e8013c0
go: `go version go1.11.6 linux/amd64`

#### System
OS: `Debian GNU/Linux 10 (buster)`
Type: CPX31 VM on Hetzner Cloud
vCPU: 4
RAM: 8GB
DISK: 160GB

## Stacktrace
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xe1f5d3, 0x16)
        /usr/lib/go-1.11/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc1cc000000, 0x8000000, 0x15dca38)
        /usr/lib/go-1.11/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x15c2ea0, 0x8000000, 0x7fa2e3ffecf0, 0x7fa2e3ffecd8)
        /usr/lib/go-1.11/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x15c2ea0, 0x3289, 0x0)
        /usr/lib/go-1.11/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x15c2ea0, 0x3289, 0x15dca48, 0x10d1000010d2)
        /usr/lib/go-1.11/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x15c2ea0, 0x3289, 0x7fa2cccd0101, 0x0)
        /usr/lib/go-1.11/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/lib/go-1.11/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x15c2ea0, 0x3289, 0x7fa2e3000101, 0x434975)
        /usr/lib/go-1.11/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x6512000, 0x7fa2e3ff0100, 0x434b47)
        /usr/lib/go-1.11/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/lib/go-1.11/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0xc0043ae480)
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/lib/go-1.11/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:311 fp=0xc02b0d7470 sp=0xc02b0d7468 pc=0x457d90
runtime.mallocgc(0x6512000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.11/src/runtime/malloc.go:913 +0x896 fp=0xc02b0d7510 sp=0xc02b0d7470 pc=0x40db46
runtime.growslice(0xc96120, 0xc1c3fea000, 0x50d9fe6, 0x50da000, 0x50da030, 0xc0fec92fa0, 0xc0fec92fd8, 0xc192991500)
        /usr/lib/go-1.11/src/runtime/slice.go:197 +0x219 fp=0xc02b0d7578 sp=0xc02b0d7510 pc=0x442be9
encoding/gob.(*encBuffer).WriteString(...)
        /usr/lib/go-1.11/src/encoding/gob/encode.go:60
encoding/gob.encString(0x0, 0xc0ae7ba800, 0xc95e60, 0xc0a0451c10, 0x98)
        /usr/lib/go-1.11/src/encoding/gob/encode.go:256 +0x170 fp=0xc02b0d75f8 sp=0xc02b0d7578 pc=0x5dfc00
encoding/gob.encodeReflectValue(0xc0ae7ba800, 0xc95e60, 0xc0a0451c10, 0x98, 0xe54510, 0x0)
        /usr/lib/go-1.11/src/encoding/gob/encode.go:363 +0xb1 fp=0xc02b0d7658 sp=0xc02b0d75f8 pc=0x5e07b1
encoding/gob.(*Encoder).encodeMap(0xc0fec92fa0, 0xc0fec92fd8, 0xcd1cc0, 0xc00038a578, 0x195, 0xe54510, 0xc13ccc8b30, 0
x0, 0x1)
        /usr/lib/go-1.11/src/encoding/gob/encode.go:374 +0x1a1 fp=0xc02b0d76f8 sp=0xc02b0d7658 pc=0x5e09c1
encoding/gob.encOpFor.func3(0xc04675a840, 0xc0ae7ba7c0, 0xcd1cc0, 0xc00038a578, 0x195)
        /usr/lib/go-1.11/src/encoding/gob/encode.go:571 +0xe4 fp=0xc02b0d7778 sp=0xc02b0d76f8 pc=0x5eb6e4
encoding/gob.(*Encoder).encodeStruct(0xc0fec92fa0, 0xc0fec92fd8, 0xc192991440, 0xda36c0, 0xc00038a500, 0x199)
        /usr/lib/go-1.11/src/encoding/gob/encode.go:328 +0x250 fp=0xc02b0d7810 sp=0xc02b0d7778 pc=0x5e0260
encoding/gob.(*Encoder).encode(0xc0fec92fa0, 0xc0fec92fd8, 0xda36c0, 0xc00038a500, 0x199, 0xc0ae7ba340)
        /usr/lib/go-1.11/src/encoding/gob/encode.go:701 +0x1cc fp=0xc02b0d7868 sp=0xc02b0d7810 pc=0x5e3a6c
encoding/gob.(*Encoder).EncodeValue(0xc0fec92fa0, 0xd41f00, 0xc00038a500, 0x16, 0x0, 0x0)
        /usr/lib/go-1.11/src/encoding/gob/encoder.go:250 +0x38d fp=0xc02b0d7920 sp=0xc02b0d7868 pc=0x5e507d
encoding/gob.(*Encoder).Encode(0xc0fec92fa0, 0xd41f00, 0xc00038a500, 0xc01c9a9a40, 0x1)
        /usr/lib/go-1.11/src/encoding/gob/encoder.go:175 +0xac fp=0xc02b0d7970 sp=0xc02b0d7920 pc=0x5e4a2c
github.com/knoxite/knoxite.(*Pipeline).Encode(0xc02b0d7a10, 0xd41f00, 0xc00038a500, 0xc192990780, 0x2, 0x2, 0x0, 0x0)
        /root/knoxite/pipeline.go:76 +0x6d fp=0xc02b0d79d0 sp=0xc02b0d7970 pc=0x6219cd
github.com/knoxite/knoxite.(*Snapshot).Save(0xc00038a500, 0xc00038a280, 0x0, 0xc13ccc8750)
        /root/knoxite/snapshot.go:266 +0x99 fp=0xc02b0d7a38 sp=0xc02b0d79d0 pc=0x6242a9
main.executeStore(0x7ffc40bc3db0, 0x6, 0xc000380290, 0x1, 0x3, 0x0, 0x0, 0x7ffc40bc3dd6, 0x4, 0x0, ...)
        /root/knoxite/cmd/knoxite/store.go:248 +0x487 fp=0xc02b0d7be8 sp=0xc02b0d7a38 pc=0xbf2bf7
main.glob..func20(0x15ae540, 0xc000380280, 0x2, 0x4, 0x0, 0x0)
        /root/knoxite/cmd/knoxite/store.go:58 +0x129 fp=0xc02b0d7c88 sp=0xc02b0d7be8 pc=0xbf5dd9
github.com/spf13/cobra.(*Command).execute(0x15ae540, 0xc000380240, 0x4, 0x4, 0x15ae540, 0xc000380240)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x473 fp=0xc02b0d7d78 sp=0xc02b0d7c88 pc=0x6eb9
f3
github.com/spf13/cobra.(*Command).ExecuteC(0x15ac320, 0xc000036031, 0x4, 0x1)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x346 fp=0xc02b0d7ec0 sp=0xc02b0d7d78 pc=0x6ec4
c6
github.com/spf13/cobra.(*Command).Execute(0x15ac320, 0x10, 0xc000036031)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887 +0x2b fp=0xc02b0d7ef0 sp=0xc02b0d7ec0 pc=0x6ec15
b
main.main()
        /root/knoxite/cmd/knoxite/main.go:81 +0x403 fp=0xc02b0d7f98 sp=0xc02b0d7ef0 pc=0xbeb563
runtime.main()
        /usr/lib/go-1.11/src/runtime/proc.go:201 +0x207 fp=0xc02b0d7fe0 sp=0xc02b0d7f98 pc=0x42e237
runtime.goexit()
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc02b0d7fe8 sp=0xc02b0d7fe0 pc=0x459e71

goroutine 5 [syscall, 32 minutes]:
os/signal.signal_recv(0x0)
        /usr/lib/go-1.11/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/lib/go-1.11/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib/go-1.11/src/os/signal/signal_unix.go:29 +0x41

goroutine 6 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x15bb640)
        /root/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
        /root/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x203

goroutine 8 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000bee60)
        /root/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
        /root/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x57

goroutine 34 [chan receive, 32 minutes]:
github.com/klauspost/shutdown2.OnSignal.func1(0xc000031c20, 0x0)
        /root/go/pkg/mod/github.com/klauspost/shutdown2@v1.1.0/shutdown.go:376 +0x5a
created by github.com/klauspost/shutdown2.OnSignal
        /root/go/pkg/mod/github.com/klauspost/shutdown2@v1.1.0/shutdown.go:375 +0x97

goroutine 7689470 [select]:
github.com/klauspost/shutdown2.Lock.func1(0xc006db0a20, 0x0, 0xc01c9aa680, 0x32, 0xc04bbf5c80, 0x15da9c0)
        /root/go/pkg/mod/github.com/klauspost/shutdown2@v1.1.0/shutdown.go:554 +0xa6
created by github.com/klauspost/shutdown2.Lock
        /root/go/pkg/mod/github.com/klauspost/shutdown2@v1.1.0/shutdown.go:553 +0x117
Command exited with non-zero status 2
```

**Comment by Prof-Bloodstone** [comment]
This doesn't seem to be cause just by the backup size - I've create 23 files with `/dev/urandom`, each 1GB in size. It doesn't result in OOM, while original data seems to trigger it every time.

I'm having trouble finding easier reproduction steps - my next idea is generate about 1_280_000 files, each about 18Kb in size and some "complex" file structure - to mimic the original data which causes the OOM.

I'm not familiar with GO or debugging OOM errors in general, but if I can provide any more information - I'd be glad to do so.

**Comment by Prof-Bloodstone** [comment]
I have managed to reproduce it really quickly - it most probably is related to amount of files.

##### Generate test data
Looks like you can go simpler than this, since the data doesn't need to be random at all.
But this is what I used:
```sh
time for d in test-data/first{0..3}/second{0..63}/third{0..63}; do mkdir -p "${d}"; for f in file-{0..63}; do fallocate -l 18K "$d/$f" & done; printf "Waiting for %s\n" "${d}"; wait; done
```
##### Commands
```sh
root@knoxite:~# export KNOXITE_REPOSITORY=backups/oom
root@knoxite:~# export KNOXITE_PASSWORD=1234
root@knoxite:~# knoxite repo init
Created new repository at /root/backups/oom
root@knoxite:~# knoxite volume init "OOM Volume"
Volume fb22cf39 (Name: OOM Volume) created
root@knoxite:~# knoxite store latest test-data/ --compression none
<SNIP>
18.00 GiB / 18.00 GiB (1,065,221 of 1,065,221)                                                                                                                        22.83 MiB/s [#################################################] 100.00%
Snapshot 61f3f45a created: 1048576 files, 16645 dirs, 0 symlinks, 0 errors, 18.00 GiB Original Size, 18.00 KiB Storage Size
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xe1f5d3, 0x16)
	/usr/lib/go-1.11/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc1b8000000, 0x8000000, 0x15dca38)
	/usr/lib/go-1.11/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x15c2ea0, 0x8000000, 0x9000192d4e, 0x7f12deffccd8)
	/usr/lib/go-1.11/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x15c2ea0, 0x286d, 0x0)
	/usr/lib/go-1.11/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x15c2ea0, 0x286d, 0x15dca48, 0x0)
	/usr/lib/go-1.11/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x15c2ea0, 0x286d, 0xffffffffffff0101, 0x7f12deffcdb8)
	/usr/lib/go-1.11/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/lib/go-1.11/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x15c2ea0, 0x286d, 0x7f12de000101, 0x4269a0)
	/usr/lib/go-1.11/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x50da000, 0x450100, 0xc1b1b9c000)
	/usr/lib/go-1.11/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
	/usr/lib/go-1.11/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0xc0000c4180)
	/usr/lib/go-1.11/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/lib/go-1.11/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/lib/go-1.11/src/runtime/asm_amd64.s:311 fp=0xc01454f1b0 sp=0xc01454f1a8 pc=0x457d90
runtime.mallocgc(0x50da000, 0x0, 0xc1b5c49f00, 0xc0000af3e6)
	/usr/lib/go-1.11/src/runtime/malloc.go:913 +0x896 fp=0xc01454f250 sp=0xc01454f1b0 pc=0x40db46
runtime.growslice(0xc96120, 0xc1b1b9c000, 0x40adff7, 0x40ae000, 0x40ae037, 0xc95e60, 0xc160fd0e48, 0x198)
	/usr/lib/go-1.11/src/runtime/slice.go:197 +0x219 fp=0xc01454f2b8 sp=0xc01454f250 pc=0x442be9
encoding/gob.(*encBuffer).WriteString(...)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:60
encoding/gob.encString(0xc0001f8420, 0xc0000af3c0, 0xc95e60, 0xc160fd0e48, 0x198)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:256 +0x170 fp=0xc01454f338 sp=0xc01454f2b8 pc=0x5dfc00
encoding/gob.(*Encoder).encodeStruct(0xc0000de1e0, 0xc0000de218, 0xc155be8680, 0xdbc1a0, 0xc160fd0e10, 0x199)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:328 +0x250 fp=0xc01454f3d0 sp=0xc01454f338 pc=0x5e0260
encoding/gob.encOpFor.func4(0x0, 0xc000293e80, 0xdbc1a0, 0xc160fd0e10, 0x199)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:581 +0xc1 fp=0xc01454f428 sp=0xc01454f3d0 pc=0x5eb8c1
encoding/gob.(*Encoder).encodeArray(0xc0000de1e0, 0xc0000de218, 0xc80360, 0xc016fa8d68, 0x197, 0xc004424280, 0x0, 0x1, 0x0)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:351 +0x130 fp=0xc01454f498 sp=0xc01454f428 pc=0x5e0510
encoding/gob.encOpFor.func1(0xc0001f8780, 0xc000293e40, 0xc80360, 0xc016fa8d68, 0x197)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:551 +0xfa fp=0xc01454f508 sp=0xc01454f498 pc=0x5eb49a
encoding/gob.(*Encoder).encodeStruct(0xc0000de1e0, 0xc0000de218, 0xc155be8640, 0xdda0c0, 0xc016fa8d20, 0x199)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:328 +0x250 fp=0xc01454f5a0 sp=0xc01454f508 pc=0x5e0260
encoding/gob.encOpFor.func4(0x0, 0xc000293e00, 0xdda0c0, 0xc016fa8d20, 0x199)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:581 +0xc1 fp=0xc01454f5f8 sp=0xc01454f5a0 pc=0x5eb8c1
encoding/gob.encodeReflectValue(0xc000293e00, 0xcf6180, 0xc016fa8d20, 0x16, 0xc004424290, 0x1)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:363 +0xb1 fp=0xc01454f658 sp=0xc01454f5f8 pc=0x5e07b1
encoding/gob.(*Encoder).encodeMap(0xc0000de1e0, 0xc0000de218, 0xcd1cc0, 0xc00038a578, 0x195, 0xe54510, 0xc004424290, 0x0, 0x1)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:375 +0x230 fp=0xc01454f6f8 sp=0xc01454f658 pc=0x5e0a50
encoding/gob.encOpFor.func3(0xc033053d40, 0xc000293dc0, 0xcd1cc0, 0xc00038a578, 0x195)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:571 +0xe4 fp=0xc01454f778 sp=0xc01454f6f8 pc=0x5eb6e4
encoding/gob.(*Encoder).encodeStruct(0xc0000de1e0, 0xc0000de218, 0xc155be84e0, 0xda36c0, 0xc00038a500, 0x199)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:328 +0x250 fp=0xc01454f810 sp=0xc01454f778 pc=0x5e0260
encoding/gob.(*Encoder).encode(0xc0000de1e0, 0xc0000de218, 0xda36c0, 0xc00038a500, 0x199, 0xc000293940)
	/usr/lib/go-1.11/src/encoding/gob/encode.go:701 +0x1cc fp=0xc01454f868 sp=0xc01454f810 pc=0x5e3a6c
encoding/gob.(*Encoder).EncodeValue(0xc0000de1e0, 0xd41f00, 0xc00038a500, 0x16, 0x0, 0x0)
	/usr/lib/go-1.11/src/encoding/gob/encoder.go:250 +0x38d fp=0xc01454f920 sp=0xc01454f868 pc=0x5e507d
encoding/gob.(*Encoder).Encode(0xc0000de1e0, 0xd41f00, 0xc00038a500, 0xc0129afa10, 0x1)
	/usr/lib/go-1.11/src/encoding/gob/encoder.go:175 +0xac fp=0xc01454f970 sp=0xc01454f920 pc=0x5e4a2c
github.com/knoxite/knoxite.(*Pipeline).Encode(0xc01454fa10, 0xd41f00, 0xc00038a500, 0xc0112f9840, 0x2, 0x2, 0x0, 0x0)
	/root/knoxite/pipeline.go:76 +0x6d fp=0xc01454f9d0 sp=0xc01454f970 pc=0x6219cd
github.com/knoxite/knoxite.(*Snapshot).Save(0xc00038a500, 0xc00038a280, 0x0, 0xc004424110)
	/root/knoxite/snapshot.go:266 +0x99 fp=0xc01454fa38 sp=0xc01454f9d0 pc=0x6242a9
main.executeStore(0x7fff4d7e1dd1, 0x6, 0xc000076310, 0x1, 0x3, 0x0, 0x0, 0x7fff4d7e1df1, 0x4, 0x0, ...)
	/root/knoxite/cmd/knoxite/store.go:248 +0x487 fp=0xc01454fbe8 sp=0xc01454fa38 pc=0xbf2bf7
main.glob..func20(0x15ae540, 0xc000076300, 0x2, 0x4, 0x0, 0x0)
	/root/knoxite/cmd/knoxite/store.go:58 +0x129 fp=0xc01454fc88 sp=0xc01454fbe8 pc=0xbf5dd9
github.com/spf13/cobra.(*Command).execute(0x15ae540, 0xc0000762c0, 0x4, 0x4, 0x15ae540, 0xc0000762c0)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x473 fp=0xc01454fd78 sp=0xc01454fc88 pc=0x6eb9f3
github.com/spf13/cobra.(*Command).ExecuteC(0x15ac320, 0xc000036051, 0x4, 0x1)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x346 fp=0xc01454fec0 sp=0xc01454fd78 pc=0x6ec4c6
github.com/spf13/cobra.(*Command).Execute(0x15ac320, 0x10, 0xc000036051)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887 +0x2b fp=0xc01454fef0 sp=0xc01454fec0 pc=0x6ec15b
main.main()
	/root/knoxite/cmd/knoxite/main.go:81 +0x403 fp=0xc01454ff98 sp=0xc01454fef0 pc=0xbeb563
runtime.main()
	/usr/lib/go-1.11/src/runtime/proc.go:201 +0x207 fp=0xc01454ffe0 sp=0xc01454ff98 pc=0x42e237
runtime.goexit()
	/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc01454ffe8 sp=0xc01454ffe0 pc=0x459e71

goroutine 19 [syscall, 13 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.11/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/lib/go-1.11/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/go-1.11/src/os/signal/signal_unix.go:29 +0x41

goroutine 20 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x15bb640)
	/root/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/root/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x203

goroutine 22 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000d2e60)
	/root/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/root/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x57

goroutine 5 [chan receive, 13 minutes]:
github.com/klauspost/shutdown2.OnSignal.func1(0xc0000adb60, 0x0)
	/root/go/pkg/mod/github.com/klauspost/shutdown2@v1.1.0/shutdown.go:376 +0x5a
created by github.com/klauspost/shutdown2.OnSignal
	/root/go/pkg/mod/github.com/klauspost/shutdown2@v1.1.0/shutdown.go:375 +0x97
```

What I noticed is that after printing backup summary, there's no output for about 7 seconds - then the OOM stacktrace is thrown. Maybe it's some issue in the post-backup process?

**Comment by Bloodchiefy** [comment]
@Prof-Bloodstone Does the error still persist? I tried to reproduce the last error case, you mentioned, and couldn't reproduce it sadly, my last two lines of the output look like this:
```
18.00 GiB / 18.00 GiB (1,065,221 of 1,065,221)                                                                                                          11.33 MiB/s [#################################################] 100.00%
Snapshot f9d5dd34 created: 1048576 files, 16645 dirs, 0 symlinks, 0 errors, 18.00 GiB Original Size, 18.00 KiB Storage Size
```

In any case, I ran a memory profiler on that command, this figure shows, that my memory only had a spike right at the beginning (about 45MB), and then only consumed less:

![knoxite_store_oom](https://user-images.githubusercontent.com/7319651/226457592-fc2d7892-4766-4c50-8483-85eaa50dc5b1.png)

Attached find also the whole memory profiler output, this can be plotted with: https://pypi.org/project/memory-profiler/

[mprofile_20230320204104.txt](https://github.com/knoxite/knoxite/files/11022802/mprofile_20230320204104.txt) (File needs to be renamed with a `.dat` extension, so that `mprof plot` can plot it)

**Comment by Bloodchiefy** [comment]
For good measure, I also ran a complete restore, there I also didn't ran into an oom issue:
```
Restore done: 1048576 files, 16645 dirs, 0 symlinks, 0 errors, 18.00 GiB Original Size, 18.00 KiB Storage Size
```

Not an indicator, that this issue isn't there, but I checked it anyway ;)
