### ISSUE TITLE
segmentation violation after encounter of (broken) symlink or permission denied 

### ISSUE THREAD

**Issue by treilik** [knoxite/knoxite#189]
While storing a snapshot into a volume, a panic occured:

```
path/to/file                                                                           0B  0B/s [#>---------------------------]   0.00%
1.74 GiB / 2.13 GiB (28,210 of 39,517)                          29.44 MiB/s [#######################################>---------]  81.90%
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x639b38]

goroutine 11 [running]:
github.com/knoxite/knoxite.(*Snapshot).Add.func1(0xc0000921e0, 0xc000092180, 0xc00007e4e0, 0xc000432600, 0xc0000e8000, 0xc0004201e0)
        /home/user/go/src/github.com/knoxite/knoxite/snapshot.go:133 +0xdb8
created by github.com/knoxite/knoxite.(*Snapshot).Add
        /home/user/go/src/github.com/knoxite/knoxite/snapshot.go:129 +0x1a7
knoxite -r /path/to/repo store volume_id path -c gzip -d "test" --verbose Debug  182,82s user 7,05s system 271% cpu 1:09,84 total
```

After removing all broken symlinks and changing all file's and directory's to be readable, it did not panic anymore.

**Comment by treilik** [comment]
Got the same panic and traceback, while storing into new/other back-end.
