### ISSUE TITLE
Panic with progressbar and gzip

### ISSUE THREAD

**Issue by flibustenet** [knoxite/knoxite#21]
Trying `-c gzip` it panic when printing the progressbar
I can give more info if needed.

```
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
panic(0x7f7c00, 0xc420078f30)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
strings.Repeat(0xc420051508, 0x1, 0xfffffffffffffff2, 0x1, 0x27)
    /usr/local/go/src/strings/strings.go:420 +0x49
github.com/muesli/goprogressbar.(*ProgressBar).Print(0xc420051880)
    /home/wilk/go/src/github.com/muesli/goprogressbar/progressbar.go:87 +0x5df
main.CmdStore.store(0x0, 0x0, 0x7ffe4bc426f4, 0x4, 0x0, 0x0, 0x0, 0xa65cc0, 0xc420051b50, 0xc4200a0d00, ...)
    /home/wilk/go/src/github.com/knoxite/knoxite/knoxite/store.go:103 +0x7e3
main.CmdStore.Execute(0x0, 0x0, 0x7ffe4bc426f4, 0x4, 0x0, 0x0, 0x0, 0xa65cc0, 0xc4200ad320, 0x2, ...)
    /home/wilk/go/src/github.com/knoxite/knoxite/knoxite/store.go:157 +0x50f
main.(*CmdStore).Execute(0xc420080640, 0xc4200ad320, 0x2, 0x9, 0x1, 0x0)
    <autogenerated>:3 +0x8a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc4200b0420, 0xc42008e010, 0x9, 0x9, 0x41aed8, 0x50, 0x837340, 0x1, 0xc4200aa8c0)
    /home/wilk/go/src/github.com/jessevdk/go-flags/parser.go:315 +0x8e6
github.com/jessevdk/go-flags.(*Parser).Parse(0xc4200b0420, 0xc4200aa8c0, 0x2, 0x2, 0xc42016be90, 0xc400000000)
    /home/wilk/go/src/github.com/jessevdk/go-flags/parser.go:185 +0x74
main.main()
    /home/wilk/go/src/github.com/knoxite/knoxite/knoxite/main.go:51 +0x1c9

```

**Comment by muesli** [comment]
Looking into that tonight. Looks like a stupid progressbar mis-calculation. I assume this works when gzip-compression is disabled?

**Comment by flibustenet** [comment]
Yes, it works without gzip-compression (on the same directory of course)
It fail only on some files (maybe because they are smalls ?). I can dig alone next week if needed...

**Comment by muesli** [comment]
I have a hunch this probably happens when the compressed output is larger than the uncompressed data. Which might happen on very small files indeed. We should probably also detect that and prefer the uncompressed version for such files (and such files only).

**Comment by muesli** [comment]
Thanks for the report again! If you could confirm this is now working for you, we would very much appreciate that :)

**Comment by flibustenet** [comment]
I confirm, it's ok now !

**Comment by flibustenet** [comment]
Sorry, it crash again finally.
You can reproduce it with a file with 'xxx' for example.
```
mkdir empty
cd empty
echo "xxx">vide
knoxite -r /tmp/knx -p x store latest . -c gzip

empty                                                                                                                    28B / 4B panic: runtime error: makeslice: len out of range          
Overall Progress                                                                                                          0B / 4B [#>-----------------------------------------------]   0.00%
goroutine 1 [running]:
panic(0x801a60, 0xc4204cc150)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
strings.Repeat(0xc4204df4b0, 0x1, 0xfffffffffffffeda, 0x1, 0x156)
	/usr/local/go/src/strings/strings.go:420 +0x49
github.com/muesli/goprogressbar.(*ProgressBar).Print(0xc4204df828)
	/home/wilk/go/src/github.com/muesli/goprogressbar/progressbar.go:87 +0x5df
main.CmdStore.store(0x0, 0x0, 0x7ffda72ba5bc, 0x4, 0x0, 0x0, 0x0, 0xa76f20, 0xc4204dfb18, 0xc420087440, ...)
	/home/wilk/go/src/github.com/knoxite/knoxite/knoxite/store.go:103 +0x7e3
main.CmdStore.Execute(0x0, 0x0, 0x7ffda72ba5bc, 0x4, 0x0, 0x0, 0x0, 0xa76f20, 0xc420087320, 0x2, ...)
	/home/wilk/go/src/github.com/knoxite/knoxite/knoxite/store.go:157 +0x52d
main.(*CmdStore).Execute(0xc420018780, 0xc420087320, 0x2, 0x9, 0x1, 0x0)
	<autogenerated>:3 +0x8a
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420066480, 0xc42000c0b0, 0x9, 0x9, 0x41af78, 0x50, 0x841880, 0x1, 0xc420016910)
	/home/wilk/go/src/github.com/jessevdk/go-flags/parser.go:316 +0x8e6
github.com/jessevdk/go-flags.(*Parser).Parse(0xc420066480, 0xc420016910, 0x2, 0x2, 0xc42013be90, 0xc400000000)
	/home/wilk/go/src/github.com/jessevdk/go-flags/parser.go:186 +0x74
main.main()
	/home/wilk/go/src/github.com/knoxite/knoxite/knoxite/main.go:51 +0x1c9

```

**Comment by muesli** [comment]
Sorry for the regression, but this should be fixed for good now. Although being a good indicator that something was incorrectly calculated, I might additionally add checks to the progress-bar implementation to prevent this from ever panic'ing again.
